// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qicomzwfiudggpubcsgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpY29tendmaXVkZ2dwdWJjc2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjkxNjksImV4cCI6MjA1OTYwNTE2OX0.zmDveKynL-GnsACJESyXbXoCZmTj7j3y-h7u-ypuWOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);